### ISSUE TITLE
Long term maintenance of mangal

### ISSUE THREAD

**Issue by luevano** [Belphemur/mangal#45]
Hi, sorry to open an "issue" just to ask this, but I don't can't find an email to contact you.

I know the original maintainer owner metafates basically abandoned the project, and I've seen your fork being updated constantly, even saw the "ownership" change commit, I haven't followed the latest changes since a couple of weeks, but I'm interested.

I just want to know what is your medium/long term commitment to maintain it? I can contribute, too, as I've also made some changes that I needed/fixed, but yours is more advanced at this point and if I can just rely on yours and contribute, then I can ditch mine (just a couple of fixes).

Let me know if you want to chat further, you can send me an email: david@luevano.xyz

**Comment by Belphemur** [comment]
Hi @luevano,

I just realized I missed your comment.

Currently, I admit, it's mostly adding a couple of feature I wanted, and I mostly use it with Kaizoku, so I wanted to fix any issue relating to their interoperability.

I'll contact you by email, could be interesting to collaborate on this.

**Comment by luevano** [comment]
Hey, I was too busy the last couple of weeks. Sure, I'll move our communication over there. But as a head up, it looks like metafates is actually working on "v5" (look at the branches), so maybe it's worth a wait? I didn't work much myself on mangal as it was a bit too much of a codebase for me, looks like he's doing a rewrite.

**Comment by umop3plsdn** [comment]
seeing as he didn't really progress any more and abandoned v5 i saw that you picked up some about 6 months ago. Do you have any ambition to takeover the project?

**Comment by Belphemur** [comment]
Not really :) 
I've moved to use https://github.com/Suwayomi/Suwayomi-Server for my needs. I don't have to maintain anything and it works perfectly with access to all sources of Mihon.

**Comment by umop3plsdn** [comment]
oooh nice thank you for that
